In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
account_df = pd.read_csv("data/account.csv", sep=";")
card_df    = pd.read_csv("data/card.csv",    sep=";")
client_df  = pd.read_csv("data/client.csv",  sep=";")
disp_df    = pd.read_csv("data/disp.csv",    sep=";")
district_df= pd.read_csv("data/district.csv",sep=";")
loan_df    = pd.read_csv("data/loan.csv",    sep=";")
order_df   = pd.read_csv("data/order.csv",   sep=";")
trans_df   = pd.read_csv("data/trans.csv",   sep=";", low_memory=False)

In [3]:
loan_df

     loan_id  account_id    date  amount  duration  payments status
0       5314        1787  930705   96396        12    8033.0      B
1       5316        1801  930711  165960        36    4610.0      A
2       6863        9188  930728  127080        60    2118.0      A
3       5325        1843  930803  105804        36    2939.0      A
4       7240       11013  930906  274740        60    4579.0      A
..       ...         ...     ...     ...       ...       ...    ...
677     4989         105  981205  352704        48    7348.0      C
678     5221        1284  981205   52512        12    4376.0      C
679     6402        6922  981206  139488        24    5812.0      C
680     5346        1928  981206   55632        24    2318.0      C
681     6748        8645  981208  240900        60    4015.0      C

[682 rows x 7 columns]

In [4]:
loan_df["date"] = pd.to_datetime(loan_df["date"], format="%y%m%d")

In [5]:
loan_df.head()

   loan_id  account_id       date  amount  duration  payments status
0     5314        1787 1993-07-05   96396        12    8033.0      B
1     5316        1801 1993-07-11  165960        36    4610.0      A
2     6863        9188 1993-07-28  127080        60    2118.0      A
3     5325        1843 1993-08-03  105804        36    2939.0      A
4     7240       11013 1993-09-06  274740        60    4579.0      A

In [6]:
trans_df.head()

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN

In [7]:
trans_df.dtypes

trans_id        int64
account_id      int64
date            int64
type           object
operation      object
amount        float64
balance       float64
k_symbol       object
bank           object
account       float64
dtype: object

In [8]:
trans_df["k_symbol"].value_counts(dropna=False)

k_symbol
NaN            481881
UROK           183114
SLUZBY         155832
SIPO           118065
                53433
DUCHOD          30338
POJISTNE        18500
UVER            13580
SANKC. UROK      1577
Name: count, dtype: int64

In [9]:
district_df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
0,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
1,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
2,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813
3,4,Kladno,central Bohemia,149893,63,29,6,2,6,67.4,9753,4.64,5.05,109,5244,5892
4,5,Kolin,central Bohemia,95616,65,30,4,1,6,51.4,9307,3.85,4.43,118,2616,3040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,Opava,north Moravia,182027,17,49,12,2,7,56.4,8746,3.33,3.74,90,4355,4433
73,74,Ostrava - mesto,north Moravia,323870,0,0,0,1,1,100.0,10673,4.75,5.44,100,18782,18347
74,75,Prerov,north Moravia,138032,67,30,4,2,5,64.6,8819,5.38,5.66,99,4063,4505
75,76,Sumperk,north Moravia,127369,31,32,13,2,7,51.2,8369,4.73,5.88,107,3736,2807
76,77,Vsetin,north Moravia,148545,8,35,12,3,4,53.5,8909,4.01,5.56,113,3460,3590

## TRANSACTION DF PER MONTH

In [10]:
trans_df.head()

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN

In [11]:
trans_df.shape

(1056320, 10)

In [12]:
trans_df.groupby("account_id").value_counts()

account_id  trans_id  date    type   operation       amount  balance  k_symbol  bank  account
1           58        950905  VYDAJ  PREVOD NA UCET  2452.0  19035.3  SIPO      YZ    87144583.0    1
            59        951005  VYDAJ  PREVOD NA UCET  2452.0  19639.2  SIPO      YZ    87144583.0    1
            60        951105  VYDAJ  PREVOD NA UCET  2452.0  18042.1  SIPO      YZ    87144583.0    1
            61        951205  VYDAJ  PREVOD NA UCET  2452.0  16569.6  SIPO      YZ    87144583.0    1
            62        960105  VYDAJ  PREVOD NA UCET  2452.0  15511.0  SIPO      YZ    87144583.0    1
                                                                                                   ..
11362       3424232   980812  VYDAJ  PREVOD NA UCET  5392.0  36125.5  UVER      MN    61540514.0    1
            3424233   980912  VYDAJ  PREVOD NA UCET  5392.0  33623.8  UVER      MN    61540514.0    1
            3424234   981012  VYDAJ  PREVOD NA UCET  5392.0  31501.9  UVER      MN    61540514.0    1
            3424235   981112  VYDAJ  PREVOD NA UCET  5392.0  31308.7  UVER      MN    61540514.0    1
            3424236   981212  VYDAJ  PREVOD NA UCET  5392.0  41247.8  UVER      MN    61540514.0    1
Name: count, Length: 230465, dtype: int64

In [13]:
trans_df.isnull().sum()

trans_id           0
account_id         0
date               0
type               0
operation     183114
amount             0
balance            0
k_symbol      481881
bank          782812
account       760931
dtype: int64

In [14]:
trans_df["date"] = pd.to_datetime(trans_df["date"], format="%y%m%d")
trans_df["year_month"] = trans_df["date"].dt.to_period("M")

In [15]:
trans_df["k_symbol"] = trans_df["k_symbol"].astype(str).str.strip()
trans_df["k_symbol"] = trans_df["k_symbol"].replace({"nan": np.nan, "": np.nan})

In [16]:
trans_df["credit_amount"] = np.where(trans_df["type"] == "PRIJEM", trans_df["amount"], 0)
trans_df["debit_amount"]  = np.where(trans_df["type"] != "PRIJEM", trans_df["amount"], 0)

In [17]:
trans_df["k_symbol"].value_counts()

k_symbol
UROK           183114
SLUZBY         155832
SIPO           118065
DUCHOD          30338
POJISTNE        18500
UVER            13580
SANKC. UROK      1577
Name: count, dtype: int64

In [18]:
# one-hot encoding for k_symbol

ksym_flags = pd.get_dummies(trans_df["k_symbol"], prefix="ksym")
trans_df = pd.concat([trans_df, ksym_flags], axis=1)

In [19]:
trans_df

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account,year_month,credit_amount,debit_amount,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,ksym_SLUZBY,ksym_UROK,ksym_UVER
0,695247,2378,1993-01-01,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN,1993-01,700.0,0.0,False,False,False,False,False,False,False
1,171812,576,1993-01-01,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN,1993-01,900.0,0.0,False,False,False,False,False,False,False
2,207264,704,1993-01-01,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN,1993-01,1000.0,0.0,False,False,False,False,False,False,False
3,1117247,3818,1993-01-01,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN,1993-01,600.0,0.0,False,False,False,False,False,False,False
4,579373,1972,1993-01-02,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN,1993-01,400.0,0.0,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,1998-12-31,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN,1998-12,62.3,0.0,False,False,False,False,False,True,False
1056316,3627616,2935,1998-12-31,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN,1998-12,81.3,0.0,False,False,False,False,False,True,False
1056317,3625403,2869,1998-12-31,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN,1998-12,60.2,0.0,False,False,False,False,False,True,False
1056318,3626683,2907,1998-12-31,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN,1998-12,107.5,0.0,False,False,False,False,False,True,False
1056319,3626540,2902,1998-12-31,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN,1998-12,164.1,0.0,False,False,False,False,False,True,False

In [20]:
agg_dict = {
    "credit_amount": "sum",
    "debit_amount": "sum",
    "trans_id": "count",
    "balance": "last",
}
agg_dict.update({col: "sum" for col in ksym_flags.columns})

monthly_panel = (
    trans_df.sort_values("date")
    .groupby(["account_id", "year_month"])
    .agg(agg_dict)
    .rename(columns={"trans_id": "n_transactions", "balance": "end_of_month_balance"})
    .reset_index()
)

monthly_panel["net_flow"] = monthly_panel["credit_amount"] - monthly_panel["debit_amount"]

In [21]:
monthly_panel.head(10)

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,ksym_SLUZBY,ksym_UROK,ksym_UVER,net_flow
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,0,0,0,1000.0
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,0,1,0,16298.2
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,0,1,0,5858.0
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,0,1,0,3579.6
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,0,1,0,-1512.1
5,1,1995-08,3778.2,7514.6,4,21501.9,0,0,0,0,1,1,0,-3736.4
6,1,1995-09,3770.5,3166.6,5,22105.8,0,0,0,1,1,1,0,603.9
7,1,1995-10,3769.5,5366.6,5,20508.7,0,0,0,1,1,1,0,-1597.1
8,1,1995-11,3764.2,5236.6,6,19906.2,0,0,0,1,1,1,0,-1472.4
9,1,1995-12,3758.0,4606.6,6,18187.6,0,0,0,1,1,1,0,-848.6

In [22]:
monthly_panel = monthly_panel.sort_values(["account_id", "year_month"]).reset_index(drop=True)

WINDOW = 6      # kaç aylık geçmişe bakılacak
MIN_HISTORY_MONTHS = 6    # baseline için en az kaç ay geçmiş şart


## ortalama ve standart sapma

for col in ["credit_amount", "debit_amount", "end_of_month_balance"]:
    grp = monthly_panel.groupby("account_id")[col]
    monthly_panel[f"{col}_roll_mean"] = grp.transform(
        lambda s: s.shift(1).rolling(WINDOW, min_periods=MIN_HISTORY_MONTHS).mean()
    )
    monthly_panel[f"{col}_roll_std"] = grp.transform(
        lambda s: s.shift(1).rolling(WINDOW, min_periods=MIN_HISTORY_MONTHS).std()
    )


## z-score

for col in ["credit_amount", "debit_amount", "end_of_month_balance"]:
    monthly_panel[f"{col}_zscore"] = (
        (monthly_panel[col] - monthly_panel[f"{col}_roll_mean"])
        / monthly_panel[f"{col}_roll_std"]
    )

zscore_cols = [c for c in monthly_panel.columns if c.endswith("_zscore")]
monthly_panel[zscore_cols] = monthly_panel[zscore_cols].replace([np.inf, -np.inf], np.nan)

In [23]:
## aylık ortalama para çekme,yatırma, aylık son para için ortalama, standart sapma kolonları eklendi
monthly_panel.head()

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,...,net_flow,credit_amount_roll_mean,credit_amount_roll_std,debit_amount_roll_mean,debit_amount_roll_std,end_of_month_balance_roll_mean,end_of_month_balance_roll_std,credit_amount_zscore,debit_amount_zscore,end_of_month_balance_zscore
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,...,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,...,16298.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,...,5858.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,...,3579.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,...,-1512.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
monthly_panel.head()

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,...,net_flow,credit_amount_roll_mean,credit_amount_roll_std,debit_amount_roll_mean,debit_amount_roll_std,end_of_month_balance_roll_mean,end_of_month_balance_roll_std,credit_amount_zscore,debit_amount_zscore,end_of_month_balance_zscore
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,...,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,...,16298.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,...,5858.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,...,3579.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,...,-1512.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
monthly_panel[["account_id", "year_month", "debit_amount", "debit_amount_roll_mean",
               "debit_amount_roll_std", "debit_amount_zscore"]].head(15)

,account_id,year_month,debit_amount,debit_amount_roll_mean,debit_amount_roll_std,debit_amount_zscore
0,1,1995-03,0.0,NaN,NaN,NaN
1,1,1995-04,0.0,NaN,NaN,NaN
2,1,1995-05,0.0,NaN,NaN,NaN
3,1,1995-06,200.0,NaN,NaN,NaN
4,1,1995-07,5300.0,NaN,NaN,NaN
5,1,1995-08,7514.6,NaN,NaN,NaN
6,1,1995-09,3166.6,2169.100000,3357.655262,0.297082
7,1,1995-10,5366.6,2696.866667,3193.369061,0.836024
8,1,1995-11,5236.6,3591.300000,3034.546099,0.542190
9,1,1995-12,4606.6,4464.066667,2501.263545,0.056985
10,1,1996-01,8336.6,5198.500000,1405.936976,2.232035
11,1,1996-02,2466.6,5704.600000,1907.031201,-1.697927
12,1,1996-03,2466.6,4863.266667,2056.469467,-1.165428
13,1,1996-04,4466.6,4746.600000,2187.647138,-0.127991
14,1,1996-05,5026.6,4596.600000,2167.394749,0.198395

In [26]:
# mutlak sapmayı da hesapla
monthly_panel["debit_amount_abs_diff"] = (
    monthly_panel["debit_amount"] - monthly_panel["debit_amount_roll_mean"]
)

Z_THRESHOLD = 2.0
MIN_ABS_CHANGE = 1000  # bu tutarın altındaki sapmalar iş açısından önemsiz sayılır

monthly_panel["debit_spike_flag"] = (
    (monthly_panel["debit_amount_zscore"].abs() >= Z_THRESHOLD) &
    (monthly_panel["debit_amount_abs_diff"].abs() >= MIN_ABS_CHANGE)
)

In [27]:
monthly_panel.head(10)

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,...,credit_amount_roll_std,debit_amount_roll_mean,debit_amount_roll_std,end_of_month_balance_roll_mean,end_of_month_balance_roll_std,credit_amount_zscore,debit_amount_zscore,end_of_month_balance_zscore,debit_amount_abs_diff,debit_spike_flag
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,1,1995-08,3778.2,7514.6,4,21501.9,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,1,1995-09,3770.5,3166.6,5,22105.8,0,0,0,1,...,5393.681386,2169.100000,3357.655262,19152.633333,9474.881393,-0.367062,0.297082,0.311684,997.500000,False
7,1,1995-10,3769.5,5366.6,5,20508.7,0,0,0,1,...,5010.666257,2696.866667,3193.369061,22670.266667,3281.082682,-0.487473,0.836024,-0.658797,2669.733333,False
8,1,1995-11,3764.2,5236.6,6,19906.2,0,0,0,1,...,849.534072,3591.300000,3034.546099,23205.350000,2363.171724,-0.423467,0.542190,-1.396069,1645.300000,False
9,1,1995-12,3758.0,4606.6,6,18187.6,0,0,0,1,...,8.543399,4464.066667,2501.263545,22663.683333,2721.928041,-1.987890,0.056985,-1.644453,142.533333,False

In [28]:
# her hesabın kaçıncı ayında olduğunu işaretle (0 = ilk ay)
monthly_panel["months_of_history"] = monthly_panel.groupby("account_id").cumcount()

In [29]:
monthly_panel.head()

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,...,debit_amount_roll_mean,debit_amount_roll_std,end_of_month_balance_roll_mean,end_of_month_balance_roll_std,credit_amount_zscore,debit_amount_zscore,end_of_month_balance_zscore,debit_amount_abs_diff,debit_spike_flag,months_of_history
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,0
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,3
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,4

In [30]:
# her hesabın kaçıncı ayında olduğunu işaretle (0 = ilk ay)
monthly_panel["months_of_history"] = monthly_panel.groupby("account_id").cumcount()

def compute_spike_flag(df, col, z_threshold=2.0, min_abs_change=1000, min_history=4):
    """
    Bir sütun için tetikleyici bayrağı üretir.
    Üç şart birden sağlanmalı:
      1) istatistiksel olarak sapmalı  (|z-skor| >= z_threshold)
      2) mutlak olarak da anlamlı      (|fark| >= min_abs_change)
      3) hesap yeterince olgun          (months_of_history >= min_history)
    """
    abs_diff = df[col] - df[f"{col}_roll_mean"]
    flag = (
        (df[f"{col}_zscore"].abs() >= z_threshold) &
        (abs_diff.abs() >= min_abs_change) &
        (df["months_of_history"] >= min_history)
    )
    return flag, abs_diff

# iki sütun için de spike
monthly_panel["debit_spike_flag"], monthly_panel["debit_amount_abs_diff"] = \
    compute_spike_flag(monthly_panel, "debit_amount", min_abs_change=1000, min_history=MIN_HISTORY_MONTHS)

monthly_panel["credit_spike_flag"], monthly_panel["credit_amount_abs_diff"] = \
    compute_spike_flag(monthly_panel, "credit_amount", min_abs_change=1500, min_history=MIN_HISTORY_MONTHS)

In [31]:
monthly_panel["debit_direction"] = np.sign(monthly_panel["debit_amount_zscore"]).map({1: "up", -1: "down", 0: "flat"})
monthly_panel["credit_direction"] = np.sign(monthly_panel["credit_amount_zscore"]).map({1: "up", -1: "down", 0: "flat"})

In [34]:
## Bu ayki bakiye, kendi son 12 aylık geçmişimin yüzde kaçından daha yüksek

In [35]:
def rolling_percentile_rank(series, window=12, min_periods=6):
    def _pct_rank(x):
        if len(x) < min_periods:
            return np.nan
        current = x.iloc[-1]
        hist = x.iloc[:-1]
        return (hist < current).mean()
    return series.rolling(window, min_periods=min_periods).apply(_pct_rank, raw=False)

monthly_panel["balance_percentile"] = (
    monthly_panel.groupby("account_id")["end_of_month_balance"]
    .transform(lambda s: rolling_percentile_rank(s))
)

In [36]:
# eğer bu ayki harcama önceki ayların %80 inden fazlaysa yüksek harcama diye etiketledi, %20 sinden düşükse düşük harcama
# sustained -> 3 aydır üst üste azalma veya artma varsa sustained diye etiketliyoruz

In [37]:
HIGH_PCTL = 0.80
LOW_PCTL = 0.20

monthly_panel["high_balance_month"] = monthly_panel["balance_percentile"] >= HIGH_PCTL
monthly_panel["low_balance_month"]  = monthly_panel["balance_percentile"] <= LOW_PCTL

monthly_panel["sustained_high_balance_flag"] = (
    monthly_panel.groupby("account_id")["high_balance_month"]
    .transform(lambda s: s.rolling(3, min_periods=3).sum() == 3)
)
monthly_panel["sustained_low_balance_flag"] = (
    monthly_panel.groupby("account_id")["low_balance_month"]
    .transform(lambda s: s.rolling(3, min_periods=3).sum() == 3)
)

In [38]:
monthly_panel

,account_id,year_month,credit_amount,debit_amount,n_transactions,end_of_month_balance,ksym_DUCHOD,ksym_POJISTNE,ksym_SANKC. UROK,ksym_SIPO,...,months_of_history,credit_spike_flag,credit_amount_abs_diff,debit_direction,credit_direction,balance_percentile,high_balance_month,low_balance_month,sustained_high_balance_flag,sustained_low_balance_flag
0,1,1995-03,1000.0,0.0,1,1000.0,0,0,0,0,...,0,False,NaN,NaN,NaN,NaN,False,False,False,False
1,1,1995-04,16298.2,0.0,3,17298.2,0,0,0,0,...,1,False,NaN,NaN,NaN,NaN,False,False,False,False
2,1,1995-05,5858.0,0.0,3,23156.2,0,0,0,0,...,2,False,NaN,NaN,NaN,NaN,False,False,False,False
3,1,1995-06,3779.6,200.0,3,26735.8,0,0,0,0,...,3,False,NaN,NaN,NaN,NaN,False,False,False,False
4,1,1995-07,3787.9,5300.0,3,25223.7,0,0,0,0,...,4,False,NaN,NaN,NaN,NaN,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185052,11382,1998-08,31089.9,23479.6,7,36868.8,0,0,0,0,...,36,False,-2667.383333,down,down,0.454545,False,False,False,False
185053,11382,1998-09,31205.4,12914.6,5,55159.5,0,0,0,0,...,37,False,-2552.233333,down,down,0.636364,False,False,False,False
185054,11382,1998-10,31247.6,32014.6,6,54392.5,0,0,0,0,...,38,False,-2504.016667,down,down,0.545455,False,False,False,False
185055,11382,1998-11,31251.1,18914.6,5,66550.3,0,0,0,0,...,39,False,-2501.450000,down,down,0.818182,True,False,False,False
185056,11382,1998-12,46860.4,31900.0,5,81373.6,0,0,0,0,...,40,True,13113.850000,down,up,1.000000,True,False,False,False

In [39]:
for col in ["debit_spike_flag", "credit_spike_flag",
            "sustained_high_balance_flag", "sustained_low_balance_flag"]:
    print(col, monthly_panel[col].mean().round(3))

flagged = monthly_panel[
    monthly_panel["debit_spike_flag"] |
    monthly_panel["credit_spike_flag"] |
    monthly_panel["sustained_high_balance_flag"] |
    monthly_panel["sustained_low_balance_flag"]
]
print("combined:", len(flagged) / len(monthly_panel))

debit_spike_flag 0.104
credit_spike_flag 0.085
sustained_high_balance_flag 0.119
sustained_low_balance_flag 0.054
combined: 0.311741787665422

In [40]:
## k_symbol tetikleyicileri

## daha önce hiç yapılmayan bir ödeme türü (fatura ödemesi gibi) yokken bu ay ortaya çıkarsa "onset" tetikleyicisi
## veya ilk defa negatif bakiye ceza faizi (SANKC. UROK) -> onset

## sürekli olan bi ödeme bi anda hiç yapılmamaya başlarsa "cessation" (kesilme) tetikleyicisi

In [41]:
K_SYMBOL_COLS = [c for c in monthly_panel.columns if c.startswith("ksym_")]

trigger_records = []

for col in K_SYMBOL_COLS:
    symbol_name = col.replace("ksym_", "")
    present = (monthly_panel[col] > 0)

    seen_before = (
        monthly_panel.groupby("account_id")[col]
        .transform(lambda s: (s > 0).cumsum().shift(1, fill_value=0) > 0)
    )

    onset_flag = present & ~seen_before
    cessation_flag = (~present) & seen_before & (
        monthly_panel.groupby("account_id")[col]
        .transform(lambda s: (s > 0).shift(1, fill_value=False))
    )

    monthly_panel[f"{symbol_name}_onset_flag"] = onset_flag
    monthly_panel[f"{symbol_name}_cessation_flag"] = cessation_flag

In [42]:
for col in K_SYMBOL_COLS:
    symbol_name = col.replace("ksym_", "")
    onset_rate = monthly_panel[f"{symbol_name}_onset_flag"].mean()
    cessation_rate = monthly_panel[f"{symbol_name}_cessation_flag"].mean()
    print(f"{symbol_name:15s} onset={onset_rate:.3f}  cessation={cessation_rate:.3f}")

DUCHOD          onset=0.004  cessation=0.000
POJISTNE        onset=0.003  cessation=0.000
SANKC. UROK     onset=0.001  cessation=0.002
SIPO            onset=0.018  cessation=0.002
SLUZBY          onset=0.024  cessation=0.024
UROK            onset=0.024  cessation=0.002
UVER            onset=0.004  cessation=0.002

In [43]:
## SIPO onset -> yeni düzenlik yükümlülük
## SANKC. UROK onset -> ilk kez negatife düşme
## UVER cessation -> kredi bitmii olabilir (yeni kredi teklif fırsatı)

## TETİKLEYİCİLER

In [44]:
## Confidence nasıl hesaplanıyor — kaynağa göre farklı mantık:

## Sayısal spike'larda z-skorun büyüklüğünden türetiyoruz (0-1 aralığına sıkıştırarak)
## Sustained balance'ta persentilin kendisini kullanıyoruz (0.95 persentil = 0.95 güven)
## Onset/cessation'da bunlar zaten kategorik/kesin olaylar olduğu için sabit ama olayın niteliğine göre farklılaştırılmış bir güven değeri veriyoruz

In [45]:
records = []

# --- 1) Sayısal sapma tetikleyicileri: debit / credit spike ---
numeric_triggers = [
    {
        "flag_col": "debit_spike_flag", "zscore_col": "debit_amount_zscore",
        "direction_col": "debit_direction",
        "label_up": "unusual_spending_increase", "product_up": "ihtiyac_kredisi_taksitlendirme",
        "label_down": "unusual_spending_decrease", "product_down": None,
    },
    {
        "flag_col": "credit_spike_flag", "zscore_col": "credit_amount_zscore",
        "direction_col": "credit_direction",
        "label_up": "income_increase", "product_up": "yatirim_urunu_limit_artirimi",
        "label_down": "income_decrease", "product_down": None,
    },
]

for spec in numeric_triggers:
    sub = monthly_panel[monthly_panel[spec["flag_col"]]].copy()
    if len(sub) == 0:
        continue
    sub["trigger_type"] = np.where(sub[spec["direction_col"]] == "up", spec["label_up"], spec["label_down"])
    sub["suggested_product"] = np.where(sub[spec["direction_col"]] == "up", spec["product_up"], spec["product_down"])
    sub["confidence"] = sub[spec["zscore_col"]].abs().clip(upper=6) / 6
    sub["evidence"] = sub[spec["zscore_col"]].round(2).apply(lambda z: {"zscore": z})
    records.append(sub[["account_id", "year_month", "trigger_type", "confidence", "suggested_product", "evidence"]])

# --- 2) Kalıcı bakiye durumu tetikleyicileri ---
balance_triggers = [
    {"flag_col": "sustained_high_balance_flag", "label": "idle_cash_buildup",
     "product": "vadeli_mevduat_fon", "conf_from_pctl": True},
    {"flag_col": "sustained_low_balance_flag", "label": "liquidity_pressure",
     "product": "esnek_limit_kredi_guvence", "conf_from_pctl": False},
]

for spec in balance_triggers:
    sub = monthly_panel[monthly_panel[spec["flag_col"]]].copy()
    if len(sub) == 0:
        continue
    sub["trigger_type"] = spec["label"]
    sub["suggested_product"] = spec["product"]
    sub["confidence"] = sub["balance_percentile"] if spec["conf_from_pctl"] else 1 - sub["balance_percentile"]
    sub["evidence"] = sub["balance_percentile"].round(2).apply(lambda p: {"balance_percentile": p})
    records.append(sub[["account_id", "year_month", "trigger_type", "confidence", "suggested_product", "evidence"]])

# --- 3) k_symbol tabanlı onset / cessation tetikleyicileri ---
meaningful_onset = {
    "SIPO": ("new_recurring_bill", "esnek_odeme_bildirim_servisi", 0.75),
    "SANKC. UROK": ("first_overdraft", "ek_limit_kredi_guvence", 0.90),
    "DUCHOD": ("pension_income_started", "emekli_bankaciligi_paketi", 0.85),
}
meaningful_cessation = {
    "UVER": ("loan_paid_off", "yeni_kredi_teklifi", 0.80),
}

for symbol, (label, product, conf) in meaningful_onset.items():
    col = f"{symbol}_onset_flag"
    sub = monthly_panel[monthly_panel[col]].copy()
    if len(sub) == 0:
        continue
    sub["trigger_type"] = label
    sub["suggested_product"] = product
    sub["confidence"] = conf
    sub["evidence"] = [{"k_symbol": symbol, "event": "onset"}] * len(sub)
    records.append(sub[["account_id", "year_month", "trigger_type", "confidence", "suggested_product", "evidence"]])

for symbol, (label, product, conf) in meaningful_cessation.items():
    col = f"{symbol}_cessation_flag"
    sub = monthly_panel[monthly_panel[col]].copy()
    if len(sub) == 0:
        continue
    sub["trigger_type"] = label
    sub["suggested_product"] = product
    sub["confidence"] = conf
    sub["evidence"] = [{"k_symbol": symbol, "event": "cessation"}] * len(sub)
    records.append(sub[["account_id", "year_month", "trigger_type", "confidence", "suggested_product", "evidence"]])

# --- Birleştir ---
trigger_table = pd.concat(records, ignore_index=True)
trigger_table = trigger_table.sort_values(["account_id", "year_month"]).reset_index(drop=True)

In [46]:
print(trigger_table.shape)
trigger_table["trigger_type"].value_counts()

(71564, 6)

trigger_type
idle_cash_buildup            21962
unusual_spending_increase    16825
income_increase              15205
liquidity_pressure            9951
new_recurring_bill            3297
unusual_spending_decrease     2425
pension_income_started         740
income_decrease                529
loan_paid_off                  366
first_overdraft                264
Name: count, dtype: int64

In [47]:
trigger_table.head()

,account_id,year_month,trigger_type,confidence,suggested_product,evidence
0,1,1995-09,new_recurring_bill,0.750000,esnek_odeme_bildirim_servisi,"{'k_symbol': 'SIPO', 'event': 'onset'}"
1,1,1996-01,unusual_spending_increase,0.372006,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.23}
2,1,1996-03,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18}
3,1,1996-04,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18}
4,1,1996-05,liquidity_pressure,0.909091,esnek_limit_kredi_guvence,{'balance_percentile': 0.09}

In [48]:
trigger_table[(trigger_table["account_id"] == 1) & (trigger_table["year_month"] == "1995-07")]

Empty DataFrame
Columns: [account_id, year_month, trigger_type, confidence, suggested_product, evidence]
Index: []

In [50]:
print(trigger_table["confidence"].describe())
(trigger_table["confidence"] >= 0.99).mean()

count    71564.000000
mean         0.735266
std          0.258570
min          0.333333
25%          0.443960
50%          0.818182
75%          1.000000
max          1.000000
Name: confidence, dtype: float64

np.float64(0.31098038119725)

In [51]:
trigger_table.head()

,account_id,year_month,trigger_type,confidence,suggested_product,evidence
0,1,1995-09,new_recurring_bill,0.750000,esnek_odeme_bildirim_servisi,"{'k_symbol': 'SIPO', 'event': 'onset'}"
1,1,1996-01,unusual_spending_increase,0.372006,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.23}
2,1,1996-03,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18}
3,1,1996-04,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18}
4,1,1996-05,liquidity_pressure,0.909091,esnek_limit_kredi_guvence,{'balance_percentile': 0.09}

## DIGER DF'LERIN TRIGGER_TABLE'A ENTEGRESİ

In [52]:
account_df  = pd.read_csv("data/account.csv",  sep=";")
client_df   = pd.read_csv("data/client.csv",   sep=";")
disp_df     = pd.read_csv("data/disp.csv",     sep=";")
district_df = pd.read_csv("data/district.csv", sep=";")
loan_df     = pd.read_csv("data/loan.csv",     sep=";")
card_df     = pd.read_csv("data/card.csv",     sep=";")

In [53]:
client_df.head()

   client_id  birth_number  district_id
0          1        706213           18
1          2        450204            1
2          3        406009            1
3          4        561201            5
4          5        605703            5

In [57]:
# clien_df birth number'ları decode

def decode_birth_number(bn):
    bn = str(int(bn)).zfill(6)
    yy, mm, dd = int(bn[0:2]), int(bn[2:4]), int(bn[4:6])
    gender = "F" if mm > 50 else "M"
    if gender == "F":
        mm -= 50
    return pd.Timestamp(year=1900 + yy, month=mm, day=dd), gender

decoded = client_df["birth_number"].apply(decode_birth_number)
client_df["birth_date"] = decoded.apply(lambda x: x[0])
client_df["gender"] = decoded.apply(lambda x: x[1])

In [58]:
client_df

      client_id  birth_number  district_id birth_date gender
0             1        706213           18 1970-12-13      F
1             2        450204            1 1945-02-04      M
2             3        406009            1 1940-10-09      F
3             4        561201            5 1956-12-01      M
4             5        605703            5 1960-07-03      F
...         ...           ...          ...        ...    ...
5364      13955        456030            1 1945-10-30      F
5365      13956        430406            1 1943-04-06      M
5366      13968        680413           61 1968-04-13      M
5367      13971        626019           67 1962-10-19      F
5368      13998        535812           74 1953-08-12      F

[5369 rows x 5 columns]

In [59]:
disp_df.head()

   disp_id  client_id  account_id       type
0        1          1           1      OWNER
1        2          2           2      OWNER
2        3          3           2  DISPONENT
3        4          4           3      OWNER
4        5          5           3  DISPONENT

In [56]:
print(disp_df["type"].unique())  # önce gerçek değerleri teyit et

['OWNER' 'DISPONENT']

In [63]:
# disp_df'teki OWNER tag'li olanlarla client_df'i merge ettik, account_client created

In [60]:
owner_disp = disp_df[disp_df["type"].str.upper() == "OWNER"]
account_client = owner_disp.merge(client_df, on="client_id", suffixes=("", "_client"))
account_client = account_client.rename(columns={"district_id": "client_district_id"})
account_client = account_client[["account_id", "client_id", "birth_date", "gender", "client_district_id"]]

In [61]:
account_client

      account_id  client_id birth_date gender  client_district_id
0              1          1 1970-12-13      F                  18
1              2          2 1945-02-04      M                   1
2              3          4 1956-12-01      M                   5
3              4          6 1919-09-22      M                  12
4              5          7 1929-01-25      M                  15
...          ...        ...        ...    ...                 ...
4495       11333      13931 1942-01-01      M                   8
4496       11349      13955 1945-10-30      F                   1
4497       11359      13968 1968-04-13      M                  61
4498       11362      13971 1962-10-19      F                  67
4499       11382      13998 1953-08-12      F                  74

[4500 rows x 5 columns]

In [64]:
print(district_df.columns.tolist())  # A1..A16 gibi kriptik mi, teyit edelim

['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']

In [65]:
district_renamed = district_df.rename(columns={
    "A1": "district_id", "A2": "district_name", "A3": "region",
    "A4": "n_inhabitants", "A10": "urban_ratio", "A11": "avg_salary",
    "A12": "unemployment_95", "A13": "unemployment_96",
})[["district_id", "district_name", "region", "n_inhabitants",
    "urban_ratio", "avg_salary", "unemployment_95", "unemployment_96"]]

account_client = account_client.merge(
    district_renamed, left_on="client_district_id", right_on="district_id", how="left"
)

In [67]:
# district bilgilerini account_client'a merge'ledik
account_client.head()

,account_id,client_id,birth_date,gender,client_district_id,district_id,district_name,region,n_inhabitants,urban_ratio,avg_salary,unemployment_95,unemployment_96
0,1,1,1970-12-13,F,18,18,Pisek,south Bohemia,70699,65.3,8968,2.83,3.35
1,2,2,1945-02-04,M,1,1,Hl.m. Praha,Prague,1204953,100.0,12541,0.29,0.43
2,3,4,1956-12-01,M,5,5,Kolin,central Bohemia,95616,51.4,9307,3.85,4.43
3,4,6,1919-09-22,M,12,12,Pribram,central Bohemia,107870,58.0,8754,3.83,4.31
4,5,7,1929-01-25,M,15,15,Cesky Krumlov,south Bohemia,58796,51.9,9045,3.13,3.60

In [68]:
loan_df.head()

   loan_id  account_id    date  amount  duration  payments status
0     5314        1787  930705   96396        12    8033.0      B
1     5316        1801  930711  165960        36    4610.0      A
2     6863        9188  930728  127080        60    2118.0      A
3     5325        1843  930803  105804        36    2939.0      A
4     7240       11013  930906  274740        60    4579.0      A

In [69]:
loan_flags = loan_df[["account_id", "status", "amount", "duration", "date"]].rename(
    columns={"status": "loan_status", "amount": "loan_amount",
             "duration": "loan_duration", "date": "loan_start_date"}
)

In [71]:
loan_flags["loan_start_date"] = pd.to_datetime(loan_flags["loan_start_date"], format="%y%m%d")
loan_flags["has_loan"] = True
loan_flags["loan_at_risk"] = loan_flags["loan_status"].isin(["B", "D"])

In [74]:
loan_flags

,account_id,loan_status,loan_amount,loan_duration,loan_start_date,has_loan,loan_at_risk
0,1787,B,96396,12,1993-07-05,True,True
1,1801,A,165960,36,1993-07-11,True,False
2,9188,A,127080,60,1993-07-28,True,False
3,1843,A,105804,36,1993-08-03,True,False
4,11013,A,274740,60,1993-09-06,True,False
...,...,...,...,...,...,...,...
677,105,C,352704,48,1998-12-05,True,False
678,1284,C,52512,12,1998-12-05,True,False
679,6922,C,139488,24,1998-12-06,True,False
680,1928,C,55632,24,1998-12-06,True,False
681,8645,C,240900,60,1998-12-08,True,False

In [75]:
card_with_account = card_df.merge(disp_df[["disp_id", "account_id"]], on="disp_id")
card_flags = card_with_account[["account_id", "type"]].rename(columns={"type": "card_type"})
card_flags["has_card"] = True
card_flags = card_flags.drop_duplicates(subset="account_id")  # bir hesapta birden fazla kart varsa ilkini al

In [76]:
card_flags

     account_id card_type  has_card
0          7753   classic      True
1           489   classic      True
2          4078   classic      True
3           361   classic      True
4          3050   classic      True
..          ...       ...       ...
887         577      gold      True
888        3614   classic      True
889        1698   classic      True
890        3705   classic      True
891        3377   classic      True

[892 rows x 3 columns]

In [77]:
account_df["account_open_date"] = pd.to_datetime(account_df["date"], format="%y%m%d")

In [78]:
account_df

      account_id  district_id         frequency    date account_open_date
0            576           55  POPLATEK MESICNE  930101        1993-01-01
1           3818           74  POPLATEK MESICNE  930101        1993-01-01
2            704           55  POPLATEK MESICNE  930101        1993-01-01
3           2378           16  POPLATEK MESICNE  930101        1993-01-01
4           2632           24  POPLATEK MESICNE  930102        1993-01-02
...          ...          ...               ...     ...               ...
4495         124           55  POPLATEK MESICNE  971228        1997-12-28
4496        3958           59  POPLATEK MESICNE  971228        1997-12-28
4497         777           30  POPLATEK MESICNE  971228        1997-12-28
4498        1573           63  POPLATEK MESICNE  971229        1997-12-29
4499        3276            1  POPLATEK MESICNE  971229        1997-12-29

[4500 rows x 5 columns]

## TRIGGER_TABLE'I ZENGINLESTIRME

In [95]:
enriched = trigger_table.merge(account_client, on="account_id", how="left")
enriched = enriched.merge(account_df[["account_id", "account_open_date"]], on="account_id", how="left")
enriched = enriched.merge(
    loan_flags[["account_id", "has_loan", "loan_status", "loan_at_risk", "loan_start_date"]],
    on="account_id", how="left"
)
enriched = enriched.merge(card_flags[["account_id", "has_card", "card_type"]], on="account_id", how="left")

enriched["has_loan"] = enriched["has_loan"].fillna(False)
enriched["loan_at_risk"] = enriched["loan_at_risk"].fillna(False)
enriched["has_card"] = enriched["has_card"].fillna(False)

enriched["trigger_month_ts"] = enriched["year_month"].dt.to_timestamp()
enriched["account_age_months"] = (
    (enriched["trigger_month_ts"].dt.year - enriched["account_open_date"].dt.year) * 12 +
    (enriched["trigger_month_ts"].dt.month - enriched["account_open_date"].dt.month)
)
enriched["age_at_trigger"] = (
    (enriched["trigger_month_ts"] - enriched["birth_date"]).dt.days / 365.25
).round(1)

enriched["loan_age_months_at_trigger"] = np.where(
    enriched["has_loan"],
    ((enriched["trigger_month_ts"].dt.year - enriched["loan_start_date"].dt.year) * 12 +
     (enriched["trigger_month_ts"].dt.month - enriched["loan_start_date"].dt.month)),
    np.nan
)

/var/folders/2z/xs3bm4js3jn6l5zn5xw8k2pw0000gn/T/ipykernel_75583/3450167173.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  enriched["has_loan"] = enriched["has_loan"].fillna(False)
/var/folders/2z/xs3bm4js3jn6l5zn5xw8k2pw0000gn/T/ipykernel_75583/3450167173.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  enriched["loan_at_risk"] = enriched["loan_at_risk"].fillna(False)
/var/folders/2z/xs3bm4js3jn6l5zn5xw8k2pw0000gn/T/ipykernel_75583/3450167173.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  enriched["has_card"] = enriched["has_card"].fillna(False)

In [86]:
print(enriched.shape, trigger_table.shape)
enriched[["account_id", "year_month", "trigger_type", "gender", "age_at_trigger",
          "district_name", "avg_salary", "has_loan", "has_card", "account_age_months"]].head(10)

(71564, 29) (71564, 6)

,account_id,year_month,trigger_type,gender,age_at_trigger,district_name,avg_salary,has_loan,has_card,account_age_months
0,1,1995-09,new_recurring_bill,F,24.7,Pisek,8968,False,False,6
1,1,1996-01,unusual_spending_increase,F,25.1,Pisek,8968,False,False,10
2,1,1996-03,liquidity_pressure,F,25.2,Pisek,8968,False,False,12
3,1,1996-04,liquidity_pressure,F,25.3,Pisek,8968,False,False,13
4,1,1996-05,liquidity_pressure,F,25.4,Pisek,8968,False,False,14
5,1,1996-08,income_increase,F,25.6,Pisek,8968,False,False,17
6,1,1997-02,unusual_spending_decrease,F,26.1,Pisek,8968,False,False,23
7,1,1997-03,unusual_spending_increase,F,26.2,Pisek,8968,False,False,24
8,1,1997-04,unusual_spending_decrease,F,26.3,Pisek,8968,False,False,25
9,1,1997-05,liquidity_pressure,F,26.4,Pisek,8968,False,False,26

In [87]:
enriched[enriched["has_loan"]][["account_id", "year_month", "loan_start_date", "loan_status", "loan_age_months_at_trigger"]].head(10)

,account_id,year_month,loan_start_date,loan_status,loan_age_months_at_trigger
14,2,1993-08,1994-01-05,A,-5.0
15,2,1993-12,1994-01-05,A,-1.0
16,2,1994-06,1994-01-05,A,5.0
17,2,1994-12,1994-01-05,A,11.0
18,2,1995-01,1994-01-05,A,12.0
19,2,1995-06,1994-01-05,A,17.0
20,2,1995-08,1994-01-05,A,19.0
21,2,1995-12,1994-01-05,A,23.0
22,2,1996-01,1994-01-05,A,24.0
23,2,1996-06,1994-01-05,A,29.0

In [83]:
print(enriched["has_loan"].mean(), enriched["has_card"].mean())
print(loan_flags["account_id"].nunique(), "/ 4500 hesapta kredi")
print(card_flags["account_id"].nunique(), "/ 4500 hesapta kart")

0.1394555921971941 0.21119557319322566
682 / 4500 hesapta kredi
892 / 4500 hesapta kart

In [96]:
loan_holders = enriched[enriched["has_loan"]]
pre_loan_triggers = loan_holders[loan_holders["loan_age_months_at_trigger"] < 0]
print(f"Kredi öncesi tetiklenen satır sayısı: {len(pre_loan_triggers)}")
pre_loan_triggers["trigger_type"].value_counts()

Kredi öncesi tetiklenen satır sayısı: 2103

trigger_type
unusual_spending_increase    584
income_increase              550
new_recurring_bill           409
idle_cash_buildup            226
liquidity_pressure           201
unusual_spending_decrease     75
income_decrease               29
first_overdraft               29
Name: count, dtype: int64

In [89]:
enriched.head()

,account_id,year_month,trigger_type,confidence,suggested_product,evidence,client_id,birth_date,gender,client_district_id,...,has_loan,loan_status,loan_at_risk,loan_start_date,has_card,card_type,trigger_month_ts,account_age_months,age_at_trigger,loan_age_months_at_trigger
0,1,1995-09,new_recurring_bill,0.750000,esnek_odeme_bildirim_servisi,"{'k_symbol': 'SIPO', 'event': 'onset'}",1,1970-12-13,F,18,...,False,NaN,NaN,NaT,False,NaN,1995-09-01,6,24.7,NaN
1,1,1996-01,unusual_spending_increase,0.372006,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.23},1,1970-12-13,F,18,...,False,NaN,NaN,NaT,False,NaN,1996-01-01,10,25.1,NaN
2,1,1996-03,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,False,NaN,NaN,NaT,False,NaN,1996-03-01,12,25.2,NaN
3,1,1996-04,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,False,NaN,NaN,NaT,False,NaN,1996-04-01,13,25.3,NaN
4,1,1996-05,liquidity_pressure,0.909091,esnek_limit_kredi_guvence,{'balance_percentile': 0.09},1,1970-12-13,F,18,...,False,NaN,NaN,NaT,False,NaN,1996-05-01,14,25.4,NaN

## KREDI ALIMINDAN ONCE DAHA SIK GORULUYOR MU?

In [97]:
baseline_dist = enriched["trigger_type"].value_counts(normalize=True)
preloan_dist = pre_loan_triggers["trigger_type"].value_counts(normalize=True)

lift_table = pd.DataFrame({
    "baseline_share": baseline_dist,
    "pre_loan_share": preloan_dist
}).dropna()

lift_table["lift"] = lift_table["pre_loan_share"] / lift_table["baseline_share"]
lift_table.sort_values("lift", ascending=False)

                           baseline_share  pre_loan_share      lift
trigger_type
new_recurring_bill               0.046071        0.194484  4.221431
first_overdraft                  0.003689        0.013790  3.738087
income_decrease                  0.007392        0.013790  1.865510
income_increase                  0.212467        0.261531  1.230925
unusual_spending_increase        0.235104        0.277699  1.181172
unusual_spending_decrease        0.033886        0.035663  1.052458
liquidity_pressure               0.139050        0.095578  0.687361
idle_cash_buildup                0.306886        0.107466  0.350180

In [99]:
window_months = 6
near_loan = enriched[
    enriched["has_loan"] &
    (enriched["loan_age_months_at_trigger"] >= -window_months) &
    (enriched["loan_age_months_at_trigger"] <= window_months)
].copy()

near_loan["period"] = np.where(near_loan["loan_age_months_at_trigger"] < 0, "before", "after")

pd.crosstab(near_loan["trigger_type"], near_loan["period"], normalize="columns")

period                        after    before
trigger_type
first_overdraft            0.012076  0.017442
idle_cash_buildup          0.151811  0.130399
income_decrease            0.025302  0.014950
income_increase            0.307073  0.281561
liquidity_pressure         0.165037  0.120432
loan_paid_off              0.018401  0.000000
new_recurring_bill         0.032202  0.125415
unusual_spending_decrease  0.043128  0.039867
unusual_spending_increase  0.244968  0.269934

In [92]:
# sistem krediye ihtiyacı önceden sezebiliyor mu? -> sadece new_recurring_bill için güçlü çıktı diğerleri zayıf

## OFFER RATE -> loan_at_risk'te olanlar daha fazla çıkmalı trigger type'a göre

In [100]:
CREDIT_TRIGGERS = ["unusual_spending_increase", "first_overdraft", "liquidity_pressure"]
median_salary = enriched["avg_salary"].median()

def assign_offer_rate(row):
    base_rate = 2.49
    risk_adj = 0.50 if row["loan_at_risk"] else (-0.30 if row["has_loan"] and row["loan_status"] == "A" else 0.0)
    segment_adj = -0.10 if row["avg_salary"] >= median_salary else 0.0
    return round(base_rate + risk_adj + segment_adj, 2)

# tek satır: sadece kredi tetikleyicili satırlara uygula, diğerleri NaN kalsın
enriched["offer_rate"] = enriched.apply(lambda r: assign_offer_rate(r) if r["trigger_type"] in CREDIT_TRIGGERS else np.nan, axis=1)

In [104]:
enriched["offer_rate"] = enriched.apply(lambda r: assign_offer_rate(r) if r["trigger_type"] in CREDIT_TRIGGERS else np.nan, axis=1)

In [105]:
enriched[enriched["trigger_type"].isin(CREDIT_TRIGGERS)][
    ["account_id", "trigger_type", "has_loan", "loan_status", "loan_at_risk", "avg_salary", "offer_rate"]
].head(10)

,account_id,trigger_type,has_loan,loan_status,loan_at_risk,avg_salary,offer_rate
1,1,unusual_spending_increase,False,NaN,False,8968,2.49
2,1,liquidity_pressure,False,NaN,False,8968,2.49
3,1,liquidity_pressure,False,NaN,False,8968,2.49
4,1,liquidity_pressure,False,NaN,False,8968,2.49
7,1,unusual_spending_increase,False,NaN,False,8968,2.49
9,1,liquidity_pressure,False,NaN,False,8968,2.49
11,1,unusual_spending_increase,False,NaN,False,8968,2.49
13,1,unusual_spending_increase,False,NaN,False,8968,2.49
18,2,unusual_spending_increase,True,A,False,12541,2.09
20,2,unusual_spending_increase,True,A,False,12541,2.09

In [102]:
enriched["offer_rate"] = enriched.apply(lambda r: assign_offer_rate(r) if r["trigger_type"] in CREDIT_TRIGGERS else np.nan, axis=1)

In [106]:
enriched

,account_id,year_month,trigger_type,confidence,suggested_product,evidence,client_id,birth_date,gender,client_district_id,...,loan_status,loan_at_risk,loan_start_date,has_card,card_type,trigger_month_ts,account_age_months,age_at_trigger,loan_age_months_at_trigger,offer_rate
0,1,1995-09,new_recurring_bill,0.750000,esnek_odeme_bildirim_servisi,"{'k_symbol': 'SIPO', 'event': 'onset'}",1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1995-09-01,6,24.7,NaN,NaN
1,1,1996-01,unusual_spending_increase,0.372006,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.23},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-01-01,10,25.1,NaN,2.49
2,1,1996-03,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-03-01,12,25.2,NaN,2.49
3,1,1996-04,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-04-01,13,25.3,NaN,2.49
4,1,1996-05,liquidity_pressure,0.909091,esnek_limit_kredi_guvence,{'balance_percentile': 0.09},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-05-01,14,25.4,NaN,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71559,11382,1998-01,unusual_spending_increase,0.557933,ihtiyac_kredisi_taksitlendirme,{'zscore': 3.35},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-01-01,29,44.4,NaN,2.39
71560,11382,1998-05,idle_cash_buildup,1.000000,vadeli_mevduat_fon,{'balance_percentile': 1.0},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-05-01,33,44.7,NaN,NaN
71561,11382,1998-06,unusual_spending_increase,0.422305,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.53},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-06-01,34,44.8,NaN,2.39
71562,11382,1998-06,income_increase,0.339652,yatirim_urunu_limit_artirimi,{'zscore': 2.04},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-06-01,34,44.8,NaN,NaN
71563,11382,1998-12,income_increase,0.345125,yatirim_urunu_limit_artirimi,{'zscore': 2.07},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-12-01,40,45.3,NaN,NaN

In [107]:
null_summary = enriched.isna().sum().sort_values(ascending=False)
null_summary[null_summary > 0]

loan_age_months_at_trigger    61584
loan_start_date               61584
loan_status                   61584
card_type                     56450
offer_rate                    44524
suggested_product              2954
dtype: int64

In [108]:
marketing_ready = enriched[enriched["suggested_product"].notna()].copy()
print("Tüm analitik tablo:", enriched.shape)
print("Pazarlamaya uygun tablo:", marketing_ready.shape)

Tüm analitik tablo: (71564, 30)
Pazarlamaya uygun tablo: (68610, 30)

In [109]:
marketing_ready

,account_id,year_month,trigger_type,confidence,suggested_product,evidence,client_id,birth_date,gender,client_district_id,...,loan_status,loan_at_risk,loan_start_date,has_card,card_type,trigger_month_ts,account_age_months,age_at_trigger,loan_age_months_at_trigger,offer_rate
0,1,1995-09,new_recurring_bill,0.750000,esnek_odeme_bildirim_servisi,"{'k_symbol': 'SIPO', 'event': 'onset'}",1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1995-09-01,6,24.7,NaN,NaN
1,1,1996-01,unusual_spending_increase,0.372006,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.23},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-01-01,10,25.1,NaN,2.49
2,1,1996-03,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-03-01,12,25.2,NaN,2.49
3,1,1996-04,liquidity_pressure,0.818182,esnek_limit_kredi_guvence,{'balance_percentile': 0.18},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-04-01,13,25.3,NaN,2.49
4,1,1996-05,liquidity_pressure,0.909091,esnek_limit_kredi_guvence,{'balance_percentile': 0.09},1,1970-12-13,F,18,...,NaN,False,NaT,False,NaN,1996-05-01,14,25.4,NaN,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71559,11382,1998-01,unusual_spending_increase,0.557933,ihtiyac_kredisi_taksitlendirme,{'zscore': 3.35},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-01-01,29,44.4,NaN,2.39
71560,11382,1998-05,idle_cash_buildup,1.000000,vadeli_mevduat_fon,{'balance_percentile': 1.0},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-05-01,33,44.7,NaN,NaN
71561,11382,1998-06,unusual_spending_increase,0.422305,ihtiyac_kredisi_taksitlendirme,{'zscore': 2.53},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-06-01,34,44.8,NaN,2.39
71562,11382,1998-06,income_increase,0.339652,yatirim_urunu_limit_artirimi,{'zscore': 2.04},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-06-01,34,44.8,NaN,NaN
71563,11382,1998-12,income_increase,0.345125,yatirim_urunu_limit_artirimi,{'zscore': 2.07},13998,1953-08-12,F,74,...,NaN,False,NaT,False,NaN,1998-12-01,40,45.3,NaN,NaN

In [116]:
marketing_ready["loan_status"].value_counts()

loan_status
C    4240
A    3735
B     683
D     681
Name: count, dtype: int64

In [113]:
print(marketing_ready.evidence.value_counts())

evidence
{'balance_percentile': 1.0}               13970
{'balance_percentile': 0.91}               4532
{'balance_percentile': 0.0}                3775
{'zscore': 2.04}                           3412
{'k_symbol': 'SIPO', 'event': 'onset'}     3297
                                          ...
{'zscore': 20.19}                             1
{'zscore': 34.02}                             1
{'zscore': 652.64}                            1
{'zscore': 40.25}                             1
{'zscore': 10.38}                             1
Name: count, Length: 2069, dtype: int64

## LLM'E GITMEDEN ONCE SON KONTROLLER

In [117]:
print("Toplam satır:", len(marketing_ready))
print("Tekil (account_id, year_month, trigger_type) kombinasyonu:",
      marketing_ready[["account_id", "year_month", "trigger_type"]].drop_duplicates().shape[0])

print("\nconfidence aralığı:", marketing_ready["confidence"].min(), "-", marketing_ready["confidence"].max())
print("confidence NaN sayısı:", marketing_ready["confidence"].isna().sum())
print("confidence 0-1 dışında kalan:", ((marketing_ready["confidence"] < 0) | (marketing_ready["confidence"] > 1)).sum())

Toplam satır: 68610
Tekil (account_id, year_month, trigger_type) kombinasyonu: 68610

confidence aralığı: 0.3333333333333333 - 1.0
confidence NaN sayısı: 0
confidence 0-1 dışında kalan: 0

In [118]:
CREDIT_TRIGGERS = ["unusual_spending_increase", "first_overdraft", "liquidity_pressure"]

wrong_place = marketing_ready[
    (~marketing_ready["trigger_type"].isin(CREDIT_TRIGGERS)) & marketing_ready["offer_rate"].notna()
]
print("Kredi dışı tetikleyicide offer_rate dolu olan (0 olmalı):", len(wrong_place))

print("offer_rate aralığı:", marketing_ready["offer_rate"].min(), "-", marketing_ready["offer_rate"].max())

Kredi dışı tetikleyicide offer_rate dolu olan (0 olmalı): 0
offer_rate aralığı: 2.09 - 2.99

In [119]:
print("age_at_trigger aralığı:", marketing_ready["age_at_trigger"].min(), "-", marketing_ready["age_at_trigger"].max())
print("year_month aralığı:", marketing_ready["year_month"].min(), "-", marketing_ready["year_month"].max())
print("account_age_months negatif olan:", (marketing_ready["account_age_months"] < 0).sum())

age_at_trigger aralığı: 10.7 - 80.9
year_month aralığı: 1993-01 - 1998-12
account_age_months negatif olan: 0

In [120]:
for t in marketing_ready["trigger_type"].unique():
    sample_evidence = marketing_ready[marketing_ready["trigger_type"] == t]["evidence"].iloc[0]
    print(f"{t:30s} -> {sample_evidence}")

new_recurring_bill             -> {'k_symbol': 'SIPO', 'event': 'onset'}
unusual_spending_increase      -> {'zscore': 2.23}
liquidity_pressure             -> {'balance_percentile': 0.18}
income_increase                -> {'zscore': 3.26}
idle_cash_buildup              -> {'balance_percentile': 1.0}
loan_paid_off                  -> {'k_symbol': 'UVER', 'event': 'cessation'}
pension_income_started         -> {'k_symbol': 'DUCHOD', 'event': 'onset'}
first_overdraft                -> {'k_symbol': 'SANKC. UROK', 'event': 'onset'}

In [121]:
marketing_ready["trigger_type"].value_counts(normalize=True).round(3)

trigger_type
idle_cash_buildup            0.320
unusual_spending_increase    0.245
income_increase              0.222
liquidity_pressure           0.145
new_recurring_bill           0.048
pension_income_started       0.011
loan_paid_off                0.005
first_overdraft              0.004
Name: proportion, dtype: float64

In [122]:
multi_trigger = marketing_ready.groupby(["account_id", "year_month"]).size()
print("Aynı ay birden fazla tetikleyicisi olan hesap-ay sayısı:", (multi_trigger > 1).sum())
print("Maksimum aynı anda tetiklenen sayı:", multi_trigger.max())

Aynı ay birden fazla tetikleyicisi olan hesap-ay sayısı: 8448
Maksimum aynı anda tetiklenen sayı: 5

In [124]:
young = marketing_ready[marketing_ready["age_at_trigger"] < 18]
print(young.shape)
young[["account_id", "year_month", "trigger_type", "gender", "age_at_trigger"]].drop_duplicates(subset="account_id")

(3534, 30)

       account_id year_month               trigger_type gender  age_at_trigger
112             9    1994-01  unusual_spending_increase      M            12.9
195            15    1994-02         new_recurring_bill      M            15.1
383            26    1994-01         new_recurring_bill      M            13.4
439            29    1995-05         new_recurring_bill      F            16.8
576            36    1993-11         new_recurring_bill      F            16.8
...           ...        ...                        ...    ...             ...
70830       10788    1994-08  unusual_spending_increase      F            17.2
70959       10906    1995-01            first_overdraft      F            16.7
71102       11013    1993-08         new_recurring_bill      M            14.9
71126       11021    1994-01            first_overdraft      M            17.8
71315       11186    1995-04         new_recurring_bill      F            14.4

[322 rows x 5 columns]

In [125]:
primary_trigger = (
    marketing_ready.sort_values("confidence", ascending=False)
    .drop_duplicates(subset=["account_id", "year_month"], keep="first")
)
print(primary_trigger.shape)

(59421, 30)

In [127]:
# 18 yaş altındakileri marketing tablomuzdan çıkardık (age < 18 olanlara pazarlama tekniği uygulamak saçma olur)

In [126]:
MIN_MARKETING_AGE = 18

before = len(marketing_ready)
marketing_ready = marketing_ready[marketing_ready["age_at_trigger"] >= MIN_MARKETING_AGE].copy()
after = len(marketing_ready)

print(f"Yaş filtresiyle çıkarılan satır: {before - after}")
print(f"Kalan satır: {after}")

Yaş filtresiyle çıkarılan satır: 3534
Kalan satır: 65076

In [129]:
primary_trigger = (
    marketing_ready.sort_values("confidence", ascending=False)
    .drop_duplicates(subset=["account_id", "year_month"], keep="first")
)
print(primary_trigger.shape)

(56493, 30)

In [130]:
print("primary_trigger içinde 18 altı kalan:", (primary_trigger["age_at_trigger"] < 18).sum())
print("primary_trigger içinde aynı (account_id, year_month) tekrarı:",
      primary_trigger.duplicated(subset=["account_id", "year_month"]).sum())

primary_trigger içinde 18 altı kalan: 0
primary_trigger içinde aynı (account_id, year_month) tekrarı: 0

## EXPORT TRIGGER COLUMNS

In [131]:
export_cols = [
    "account_id", "year_month", "trigger_type", "confidence", "suggested_product", "evidence",
    "gender", "age_at_trigger", "district_name", "avg_salary", "unemployment_95", "unemployment_96",
    "has_loan", "loan_status", "loan_at_risk", "has_card", "card_type",
    "account_age_months", "offer_rate"
]
primary_trigger[export_cols].to_csv("data/trigger_table_final.csv", index=False)

import json
sample = primary_trigger[export_cols].head(5).to_dict(orient="records")
with open("data/trigger_table_sample.json", "w", encoding="utf-8") as f:
    json.dump(sample, f, ensure_ascii=False, indent=2, default=str)

print("Export tamamlandı:", primary_trigger.shape)

Export tamamlandı: (56493, 30)